### PR TITLE
Don't show the console window at launch

### PR DESCRIPTION
**Pull request by roggif**

### CODE REVIEW

**Comment by eric2788** [comment]
Thank you for the pull request! I would like to have some testing before merging, and I am not yet have time so it maybe at tonight utc+8

**Comment by eric2788** [comment]
just tested ``--no-console`` with the console application and It just showed nothing and just ran in the background. So I think It should have an option to let users choose whether to no console.

**Comment by eric2788** [comment]
hey, can you please check the [patch/no-console](https://github.com/eric2788/pyinstaller-build/tree/patch/no-console) branch to see whether it satisfies your requirement, you can also test with tag @patch/no-console

**Comment by roggif** [comment]
Tested! It works just as expected.

I believe you're ready to merge. Thanks a lot!

**Comment by eric2788** [comment]
Ok, I will close this PR and merge the patch/no-console branch

**Pull request closed without merging**
